### PR TITLE
Make HIDAPI library access thread-safe.

### LINKED ISSUE #39: Random crashes with nothing in logs
OS: Win 10
Using HID API

When set key images onto StreamDeck buttons, the script will crash randomly. There is no pattern to this. With logger on debug on, no crash relevant output is displayed. No exceptions are raised (this can by seen by surrounding set_key_image call in try/except) and the entire script instantly exits.

### PR DESCRIPTION
**Pull request by abcminiuser**
Fixes #39 (I hope).

@Subsentient figured out that the HIDAPI library isn't threadsafe, at least on Windows. That's surprising to say the least, but that does explain the random crashes some people have seen.

This updates the HIDAPI transport bindings to use non-blocking mode, and changes the reader thread to poll at least every 50ms for new events. That allows the transport to use an exclusive lock when operating on the HIDAPI methods.

The changes in this patchset should give us thread-safe access to HIDAPI, at the cost of losing event-driven reads. On the upside, it will also ensure that all StreamDeck instances terminate their reader threads in at most 50ms.

I've also fixed up the Python enter/exit methods in `StreamDeck` so that the Python `using` syntax can be used to create a scoped lock on a StreamDeck for atomic updates. Examples scripts updated to take advantage of this.

Only tested on Windows, currently.

### CODE REVIEW

**Comment by Subsentient** [comment]
I'll test these changes in a little bit. In retrospect it does make some amount of sense that you can't read while you're writing, USB 2 is a half-duplex protocol, but you would very much have expected the Microsoft devs to account for that safely, like Linux has done. It looks like they didn't.

**Comment by Subsentient** [comment]
@abcminiuser These changes work. Makes the old hidapi dlls appear stable too. Wonder if hidapi would accept a pull request though, since there's actually a lot of memory errors in their implementation still. Makes me very nervous.

**Comment by 132ikl** [comment]
Awesome to see this fixed! Thanks so much @Subsentient and @abcminiuser. I will definitely confirm that this fixes the issue for me when I can, and will let you know if there are any other issues.

**Comment by abcminiuser** [comment]
Also tested working on Linux. Thanks guys!

**Pull request merged**
