### PR TITLE
Only do Mac HIDAPI 0.9.0 bugfix on Mac

### LINKED ISSUE #53: StreamDeckXL.get_serial_number sometimes returning wrong results
**Description**
Normally, `self.device.read_feature(0x06, 32)` will return 
```
b'\x06\x0cAAAAAAAAAAAA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

But sometimes, it will return 
```
b'\x06\x0cAAAAAAAAAAAA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
```

I'm not sure exactly what causes to get into this 'sometimes \x01' state, but I have noticed it a few times after fiddling around with things. Maybe an improper abort is causing it? I can try to find out but will have to see.

I just recently started using this program, so I can't speak to any prior behavior. But I check a recent commit 1 month ago, before it would be returning 
```
b'\x06\x0cAAAAAAAAAAAA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
But due to https://github.com/abcminiuser/python-elgato-streamdeck/commit/c047eb7c2929cd92e1f316b54516588154b6f808#diff-8fce19ef15b0c8c1aa404b2a80f62eecR237-R238, we're now sometimes getting this extra `\x01` byte at the end, which is breaking normal behavior of 
https://github.com/abcminiuser/python-elgato-streamdeck/blob/086691d40c858ee042ccf7cb3bfc8beea780be4e/src/StreamDeck/Devices/StreamDeckXL.py#L133-L142
https://github.com/abcminiuser/python-elgato-streamdeck/blob/086691d40c858ee042ccf7cb3bfc8beea780be4e/src/StreamDeck/Devices/StreamDeck.py#L92-L98

**To Reproduce**
I don't know exactly how to get the device into the state so that it returns the `\x01` byte at the end, but don't think that's too important for this issue.

**Possible fix**
I'm not familiar with device APIs like this at all, so just guessing here, but adding a check to see if the last byte is \x01 fixes the issue for me. But I'm not sure if it's ever okay for this byte to be \x01, so maybe since the comment only mentions Mac, there could be an OS check here. Or we should check for a long sequence of `'x00\x00\...\x01'` to remove possible false positive? Other ideas is maybe the `read_feature()` call or `_extract_string` function can be adjusted in StreamDeckXL.
I will make a PR for option 1 in case that solution is fine. But let me know if you want it tweaked, otherwise I will just leave it up you.

**StreamDeck Information**
StreamDeckXL

**System Information**
Linux, hidapi 0.9.0-2, python-elgato-streamdeck 0.8.2
I also have this plugged into a KVM switch USB hub, in case that's relevant.

### PR DESCRIPTION
**Pull request by theslimshaney**
Fixes #53

Not sure if this is the best solution, more info on #53

### CODE REVIEW

**Comment by abcminiuser** [comment]
I think a check for the Mac platform is the way to go rather than this one - the patch I added was to fix a known hidapi bug for the Mac specific backend, but I didn't realise it would negatively affect other platforms.

**Comment by theslimshaney** [comment]
How's that look?
Also fixed a typo I noticed (platform_seach>platform_search)

**Comment by abcminiuser** [comment]
I do wonder if we shouldn't attempt to oversize the read on non-Mac platforms as well. Does the +1 read size there cause any other issues for you?

I cannot possibly express, after looking through the source, what an utter shambles HIDAPI is, and how depressing it is that it's the defacto standard for HID access. Zero API versioning, and every release introduces different and sometimes impossible to work around bugs like the off-by-one error I'm trying to avoid here.

**Comment by theslimshaney** [comment]
The only issue I have noticed is sometimes the serial number returns `b'\x06\x0cAAAAAAAAAAAA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'` which breaks `_extract_string` call. If no one else reports this issue, we can limit the exclusion to only if Linux? Or will need some other ideas

**Comment by abcminiuser** [comment]
Sorry, mean to get back to you on this. I'm a little stumped at the moment - my gut feeling with HIDAPI is that it's too unstable to rely on the platform-provided version of the library, especially without a API to get the version to apply bug workarounds on a per-platform/per-version basis.

Ultimately I think the best way will be to distribute a pre-built version with the library, but then the matter becomes where to source it from. I don't own any Mac devices and I don't think there's any reputable built versions out on the web - Windows could use the official DLL releases and Linux is easy enough to use GCC to compile it on demand (I think).

**Comment by theslimshaney** [comment]
Maybe you could use platform version for Mac and custom version for windows and Linux? What a lovely situation 😬

**Comment by abcminiuser** [comment]
Yeah, that might be the ultimate solution. My only resistance is having to figure out the build situation - I can build HIDAPI locally on my Windows and Linux machines, but it feels a little cumbersome if I have to do that every time. I'll use your patch for now until I look into if there's a better way (e.g. compiling with Clang on both under Docker).

**Pull request merged**
